// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSGeCRaip9WLHbN4TFahlPJTP5ONXWGf4',
    appId: '1:1030884467571:web:f60e5e5d119b4057a89b06',
    messagingSenderId: '1030884467571',
    projectId: 'lifeshare-873ea',
    authDomain: 'lifeshare-873ea.firebaseapp.com',
    databaseURL: 'https://lifeshare-873ea-default-rtdb.firebaseio.com',
    storageBucket: 'lifeshare-873ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqEOgzPvzSEqA9RnrWAfcJapSmsA1N4g',
    appId: '1:1030884467571:android:f43e6851ee099ed3a89b06',
    messagingSenderId: '1030884467571',
    projectId: 'lifeshare-873ea',
    databaseURL: 'https://lifeshare-873ea-default-rtdb.firebaseio.com',
    storageBucket: 'lifeshare-873ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiaSIyvdVEdZ7IHeY6lGeorJc3-z2D9_w',
    appId: '1:1030884467571:ios:6958735148efc980a89b06',
    messagingSenderId: '1030884467571',
    projectId: 'lifeshare-873ea',
    databaseURL: 'https://lifeshare-873ea-default-rtdb.firebaseio.com',
    storageBucket: 'lifeshare-873ea.appspot.com',
    iosBundleId: 'com.example.lifeshareapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiaSIyvdVEdZ7IHeY6lGeorJc3-z2D9_w',
    appId: '1:1030884467571:ios:8438f46af343026aa89b06',
    messagingSenderId: '1030884467571',
    projectId: 'lifeshare-873ea',
    databaseURL: 'https://lifeshare-873ea-default-rtdb.firebaseio.com',
    storageBucket: 'lifeshare-873ea.appspot.com',
    iosBundleId: 'com.example.lifeshareapplication.RunnerTests',
  );
}
